{"name": "Авторизация с неверным логином или паролем", "status": "passed", "description": "При неуспешной авторизации возвращает HTTP 401 и сообщение об ошибке", "steps": [{"name": "Отправка POST на auth/login", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'bakerchristian@example.com', 'password': 'abracadabra'}"}], "start": 1718472365384, "stop": 1718472365646}], "parameters": [{"name": "field", "value": "'password'"}], "start": 1718472365384, "stop": 1718472365646, "uuid": "f506f98e-b1be-43c9-98d2-d9061f578bfb", "historyId": "b1d56c4f69aec7832ff6274084af568a", "testCaseId": "7bdec89f1358e664b0e3c7770a6f7a71", "fullName": "tests.test_auth_login.TestLoginUser#test_login_wrong_email_or_pass", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_login"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "XPMEPODW0067"}, {"name": "thread", "value": "24248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_login"}]}