{"name": "Авторизация с неверным логином или паролем", "status": "passed", "description": "При неуспешной авторизации возвращает HTTP 401 и сообщение об ошибке", "steps": [{"name": "Отправка POST на auth/login", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'acarter@example.org', 'password': 'abracadabra'}"}], "start": 1718266312653, "stop": 1718266312931}], "parameters": [{"name": "field", "value": "'password'"}], "start": 1718266312653, "stop": 1718266312932, "uuid": "75ce78a3-44d9-44a3-a86a-55250f6fc073", "historyId": "b1d56c4f69aec7832ff6274084af568a", "testCaseId": "7bdec89f1358e664b0e3c7770a6f7a71", "fullName": "tests.test_auth_login.TestLoginUser#test_login_wrong_email_or_pass", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_login"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "XPMEPODW0067"}, {"name": "thread", "value": "28304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_login"}]}