{"name": "Авторизация с неверным логином или паролем", "status": "passed", "description": "При неуспешной авторизации возвращает HTTP 401 и сообщение об ошибке", "steps": [{"name": "Отправка POST на auth/login", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'abracadabra', 'password': '5133584326'}"}], "start": 1718472364216, "stop": 1718472364459}], "parameters": [{"name": "field", "value": "'email'"}], "start": 1718472364216, "stop": 1718472364459, "uuid": "4d5d8497-183b-4cf0-87e4-53a6435e02b0", "historyId": "1617deae75183eab1e7d2aeff9d3ed03", "testCaseId": "7bdec89f1358e664b0e3c7770a6f7a71", "fullName": "tests.test_auth_login.TestLoginUser#test_login_wrong_email_or_pass", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_login"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "XPMEPODW0067"}, {"name": "thread", "value": "24248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_login"}]}